[package]
name = "cranelift_shim"
version = "0.1.0"
edition = "2024"


[dependencies]
cranelift-frontend = "0.104.1"
cranelift-codegen = "0.104.1"
cranelift-module = "0.104.1"
cranelift-object = "0.104.1"
